name: snapit-v2

on:
  issue_comment:
    types:
      - created

env:
  PNPM_VERSION: '8.15.7'

jobs:
  snapit:
    name: Snapit
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/snapit' }}
    runs-on: ubuntu-latest
    steps:
      # WARNING: DO NOT RUN ANY CUSTOM LOCAL SCRIPT BEFORE RUNNING THE SNAPIT ACTION
      # This action can be executed by 3rd party users and it should not be able to run arbitrary code from a PR.
      - name: Checkout current branch
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4.0.0
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
      - name: Do something
        run: "touch .github/test.yml"
      # - name: Create snapshot version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
